### ISSUE TITLE
Clipboard is not automatically transferred

### ISSUE THREAD

**Issue by Leahcimkrob** [IntellectualSites/ClipboardConnect#41]
### Expected behavior

The clipboard is always transferred automatically

### Actual behavior

After a few hours the clipboard will no longer be transferred automatically. But we can still transfer it manually using Commands.
Today it happened after about 10 hours.

### Steps to reproduce

Just leave the server running.

### Plugin and Datapack List

Plugins:
https://mclo.gs/eeaYHJ5

Datapacky:
[19:20:43 INFO]: There are 2 data pack(s) enabled: [vanilla (built-in)], [file/bukkit (world)]
[19:20:43 INFO]: There are no more data packs available

### Paper version

[19:21:19 INFO]: Checking version, please wait...
[19:21:19 INFO]: This server is running Paper version git-Paper-409 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 9e171ef)
You are running the latest version

### Plugin version

[19:21:59 INFO]: ClipboardConnect version 1.0.0+d3ed1d8
[19:21:59 INFO]: Authors: TheMeinerLP and OneLiteFeatherNET

### Other

Because of the issue, we are currently unable to load the clip board manually.
https://github.com/IntellectualSites/ClipboardConnect/issues/40

**Comment by Leahcimkrob** [comment]
I tried it again today.
So, I went to our city build, marked 2 positions and copied the area.
Then I went to our construction server.
But the clipboard was not transferred.
![Screenshot 2024-02-09 152151](https://github.com/IntellectualSites/ClipboardConnect/assets/70509359/ea4daa94-12de-4f0e-9809-55bf85bf844b)

**Comment by TheMeinerLP** [comment]
This message apears if the content to large and still uploading to the redis

**Comment by Leahcimkrob** [comment]
The selection was 2 Blocks....

With 7390 Blocks I get this:
On the CB I first did //copy with a selection.
Then /clipboardconnect save
This error occurred:
https://mclo.gs/YYi71xH

Then I copied an area on the construction server.
When inserting on the CB this error occurred:
https://mclo.gs/sd8ELh5

**Comment by Leahcimkrob** [comment]
![image](https://github.com/IntellectualSites/ClipboardConnect/assets/70509359/038006a7-efdb-478b-a95d-bd7b02a1ac7d)
![image](https://github.com/IntellectualSites/ClipboardConnect/assets/70509359/3a2e6966-a5b4-4d01-948e-0fc5da380936)
Message Bauserver:
![image](https://github.com/IntellectualSites/ClipboardConnect/assets/70509359/e82f0a8c-7bdd-41a3-b978-b7f7a3bcc1d1)
After this, I go to CB and get this message: Message CB:
![image](https://github.com/IntellectualSites/ClipboardConnect/assets/70509359/e62ddfb0-dadf-4b17-80f6-04fab3eb65b1)

**Comment by Leahcimkrob** [comment]
redis_version => 7.2.4
I deleted all created keys via phpRedisAdmin.
Ok, after deleting all keys it works again...
Even the automatic system worked again.
Gload also works

**Comment by Leahcimkrob** [comment]
redis_version => 7.2.4
I deleted all created keys via phpRedisAdmin.
Ok, after deleting all keys it works again...
Even the automatic system worked again.
Gload also works
